[package]
name = "es-server"
description = "EventFS AggregateStore 服务端：gRPC 服务与独立进程入口"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "eventstored"
path = "src/main.rs"

[dependencies]
es-core = { workspace = true }
es-storage = { workspace = true }
es-raft = { workspace = true }
es-proto = { workspace = true }
openraft = { workspace = true }
surrealkv = { workspace = true }
tonic = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
bincode = { workspace = true }
toml = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
# 配置文件热更新 watch（temp+rename 场景 notify 可靠捕获）
notify = "7"

[dev-dependencies]
tempfile = { workspace = true }
proptest = { workspace = true }
rcgen = { workspace = true }
libc = { workspace = true }
